export const dataProducts = [
  {
    id: 1,
    title: "Product 1",
    img: "image_url_1.jpg",
    price: 19.99,
    company: "Company A",
    info: "Information about Product 1",
    inCart: false,
    count: 0,
  },
  {
    id: 2,
    title: "Product 2",
    img: "image_url_2.jpg",
    price: 24.99,
    company: "Company B",
    info: "Information about Product 2",
    inCart: false,
    count: 0,
  },
  {
    id: 3,
    title: "Product 3",
    img: "image_url_3.jpg",
    price: 29.99,
    company: "Company C",
    info: "Information about Product 3",
    inCart: false,
    count: 0,
  },
  {
    id: 4,
    title: "Product 4",
    img: "image_url_4.jpg",
    price: 34.99,
    company: "Company D",
    info: "Information about Product 4",
    inCart: false,
    count: 0,
  },
  {
    id: 5,
    title: "Product 5",
    img: "image_url_5.jpg",
    price: 39.99,
    company: "Company E",
    info: "Information about Product 5",
    inCart: false,
    count: 0,
  },
  {
    id: 6,
    title: "Product 6",
    img: "image_url_6.jpg",
    price: 44.99,
    company: "Company F",
    info: "Information about Product 6",
    inCart: false,
    count: 0,
  },
  {
    id: 7,
    title: "Product 7",
    img: "image_url_7.jpg",
    price: 49.99,
    company: "Company G",
    info: "Information about Product 7",
    inCart: false,
    count: 0,
  },
  {
    id: 8,
    title: "Product 8",
    img: "image_url_8.jpg",
    price: 54.99,
    company: "Company H",
    info: "Information about Product 8",
    inCart: false,
    count: 0,
  },
  {
    id: 9,
    title: "Product 9",
    img: "image_url_9.jpg",
    price: 59.99,
    company: "Company I",
    info: "Information about Product 9",
    inCart: false,
    count: 0,
  },
  {
    id: 10,
    title: "Product 10",
    img: "image_url_10.jpg",
    price: 64.99,
    company: "Company J",
    info: "Information about Product 10",
    inCart: false,
    count: 0,
  },
  {
    id: 11,
    title: "Product 11",
    img: "image_url_11.jpg",
    price: 69.99,
    company: "Company K",
    info: "Information about Product 11",
    inCart: false,
    count: 0,
  },
  {
    id: 12,
    title: "Product 12",
    img: "image_url_12.jpg",
    price: 74.99,
    company: "Company L",
    info: "Information about Product 12",
    inCart: false,
    count: 0,
  },
  {
    id: 13,
    title: "Product 13",
    img: "image_url_13.jpg",
    price: 79.99,
    company: "Company M",
    info: "Information about Product 13",
    inCart: false,
    count: 0,
  },
  {
    id: 14,
    title: "Product 14",
    img: "image_url_14.jpg",
    price: 84.99,
    company: "Company N",
    info: "Information about Product 14",
    inCart: false,
    count: 0,
  },
  {
    id: 15,
    title: "Product 15",
    img: "image_url_15.jpg",
    price: 89.99,
    company: "Company O",
    info: "Information about Product 15",
    inCart: false,
    count: 0,
  },
];
